# https://aka.ms/yaml

jobs:
  - job: test
    displayName: 'Lint & Test'

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - script: flake8 --format junit-xml --output-file test-lint.xml
        displayName: 'Run Linter'

      - task: PublishTestResults@2
        displayName: 'Publish Lint Results'
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: '**/test-lint.xml'
          testRunTitle: 'Lint Results'
