name: Build, Lint, Test

on:
  push:
    branches:
      - sebastiaan/backend/cache-docker-images


jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN  }}

      - name: Cache Base Image Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.base-buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-${{ github.ref }}-
            ${{ runner.os }}-buildx-base-

      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/base.Dockerfile
          push: false
          load: true
          cache-from: |
            type=local,src=/tmp/.base-buildx-cache
            ghcr.io/python-discord/snekbox-base:latest
          cache-to: type=local,dest=/tmp/.base-buildx-cache
          tags: ghcr.io/python-discord/snekbox-base:${{ steps.sha_tag.outputs.tag }}

      - name: Show Containers
        run: docker image ls

      - name: Start Container
        run: "docker run \
          --tty \
          --detach \
          --name snekbox_test \
          --privileged \
          --hostname pdsnk-dev \
          -e PYTHONDONTWRITEBYTECODE=1 \
          -e PIPENV_PIPFILE='/snekbox/Pipfile\' \
          -e ENV=\"${PWD}/scripts/.profile\" \
          --volume \"${PWD}\":\"${PWD}\" \
          --workdir \"${PWD}\" \
          --entrypoint /bin/bash \
          ghcr.io/python-discord/snekbox-base:${{ steps.sha_tag.outputs.tag }}"

      - name: Install dependencies
        run: "docker exec snekbox_test /bin/bash -c \
          'pipenv install --system --deploy --dev'"

      - name: Run linter
        run: "docker exec snekbox_test /bin/bash -c 'flake8 \
          --format \"::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s\"'"

      - name: Disable swap memory
        run: sudo swapoff -a

      - name: Run unit tests and generate coverage report
        run: "docker exec snekbox_test /bin/bash -c \
          'coverage run -m unittest; coverage report -m'"

      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # This step will publish the coverage reports coveralls.io and
      # print a "job" link in the output of the GitHub Action
      - name: Publish coverage report to coveralls.io
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls~=2.1
          coveralls

      - name: Cache Final Image Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.final-buildx-cache
          key: ${{ runner.os }}-buildx-final-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-final-${{ github.ref }}-
            ${{ runner.os }}-buildx-final-

      - name: Push intermediate base container to registry
        run: docker push ghcr.io/python-discord/snekbox-base:${{ steps.sha_tag.outputs.tag }}

      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          build-args: |
            IMAGE_TAG=${{ steps.sha_tag.outputs.tag }}
          push: true
          cache-from: |
            type=local,src=/tmp/.base-buildx-cache
            type=local,src=/tmp/.final-buildx-cache
            ghcr.io/python-discord/snekbox:latest
          cache-to: type=local,dest=/tmp/.final-buildx-cache
          tags: ghcr.io/python-discord/snekbox:latest

      - name: Build builder image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/base.Dockerfile
          push: true
          cache-from: type=local,src=/tmp/.base-buildx-cache
          cache-to: type=local,dest=/tmp/.base-buildx-cache
          tags: ghcr.io/python-discord/snekbox:latest
