name: Build, Lint, Test

on:
  push:
    branches:
      - sebastiaan/backend/migrate-ci-to-github-actions


jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN  }}

      - name: Build base image
        run: "docker build \
          -f docker/base.Dockerfile \
          -t ghcr.io/python-discord/snekbox-base:latest \
          --cache-from ghcr.io/python-discord/snekbox-base:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          ."

      - name: Show Containers
        run: docker image ls

      - name: Build base image
        run: "docker build \
          -f docker/venv.Dockerfile \
          -t ghcr.io/python-discord/snekbox-venv:latest \
          --cache-from ghcr.io/python-discord/snekbox-venv:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          ."

      - name: Show Containers
        run: docker image ls

      - name: Start Container
        run: "docker run \
          --tty \
          --detach \
          --name snekbox_test \
          --privileged \
          --hostname pdsnk-dev \
          -e PYTHONDONTWRITEBYTECODE=1 \
          -e PIPENV_PIPFILE='/snekbox/Pipfile\' \
          -e ENV=\"${PWD}/scripts/.profile\" \
          --volume \"${PWD}\":\"${PWD}\" \
          --workdir \"${PWD}\" \
          --entrypoint /bin/bash \
          ghcr.io/python-discord/snekbox-venv:latest"

      - name: Install dependencies
        run: "docker exec snekbox_test /bin/bash -c \
          'pipenv install --system --deploy --dev'"

      - name: Run linter
        run: "docker exec snekbox_test /bin/bash -c 'flake8 \
          --format \"::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s\"'"

      - name: Disable swap memory
        run: sudo swapoff -a

      - name: Run unit tests and generate coverage report
        run: "docker exec snekbox_test /bin/bash -c \
          'coverage run -m unittest; coverage report -m'"

      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # This step will publish the coverage reports coveralls.io and
      # print a "job" link in the output of the GitHub Action
      - name: Publish coverage report to coveralls.io
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls~=2.1
          coveralls
