name: Build, Lint, Test

on:
  push:
    branches:
      - sebastiaan/backend/migrate-ci-to-github-actions


jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN  }}

      - name: Build base image
        run: "docker build \
          -f docker/base.Dockerfile \
          -t pythondiscord/snekbox-base:latest \
          ."

      - name: Show Containers
        run: docker image ls

      - name: Build base image
        run: "docker build \
          -f docker/venv.Dockerfile \
          -t pythondiscord/snekbox-venv:latest \
          ."

      - name: Show Containers
        run: docker image ls

#      - name: Start Container
#        run: 'docker run \
#          --tty \
#          --detach \
#          --name snekbox_test \
#          --privileged \
#          --hostname pdsnk-dev \
#          -e PYTHONDONTWRITEBYTECODE=1 \
#          -e PIPENV_PIPFILE="/snekbox/Pipfile" \
#          -e ENV="${PWD}/scripts/.profile" \
#          --volume "${PWD}":"${PWD}" \
#          --workdir "${PWD}"\
#          --entrypoint /bin/bash \
#          pythondiscord/snekbox-venv:latest'
#
#      - name: Install dependencies
#        run: "docker exec snekbox_test /bin/bash -c \
#          'pipenv install --system --deploy --dev'"
#
#      - name: Run linter
#        run: "docker exec snekbox_test /bin/bash -c 'flake8 \
#          --format \"::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s\"'"
