name: Lint, Test, Build, Push

on:
  push:
    branches:
      - main

jobs:
  lint-test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build final image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/ambrosebot/snekbox:latest
